on:
 push:
   branches:
   - ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: ls -la
      - run: pwd
      - run: whoami

      # - name: Deploy to Staging server
      #   uses: easingthemes/ssh-deploy@main
      #   with:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ARGS: "-rlgoDzvc -i"
      #     SOURCE: "dist/"
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}
      #     EXCLUDE: "/dist/, /node_modules/"
      #     SCRIPT_BEFORE: |
      #       whoami
      #       ls -al
      #     SCRIPT_AFTER: |
      #       whoami
      #       ls -al
      #       echo $RSYNC_STDOUT
        
