name: Deploy

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - run: ls -la

      - run: hostname -i
